name: Sync Libis

on:
  schedule:
    # Daily schedule
    - cron: '0 3 * * *'

jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
    - name: Copy iiif
      run: |
        git clone --depth=1 --branch=master https://github.com/libis/ca_tudelft_iiif
        cp -a ca_tudelft_iiif/objects/. content/objects
        cp -a ca_tudelft_iiif/collections/. content/collections/lib-library
        git rm --cached -f ca_tudelft_iiif
        rm -r ca_tudelft_iiif
        git add .
        git diff-index --quiet HEAD || git commit -m "Automatic publish from github.com/libis/ca_tudelft_iiif"
        git push target master
        
